export const cookies = [
  {
    domain: ".qidian.com",
    expirationDate: 1677772799,
    hostOnly: false,
    httpOnly: false,
    name: "traffic_utm_referer",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709296100,
    hostOnly: false,
    httpOnly: false,
    name: "showSectionCommentGuide",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "1",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1712329679.909885,
    hostOnly: false,
    httpOnly: false,
    name: "_ga",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "GA1.1.2466135.1677760100",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1680360711,
    hostOnly: false,
    httpOnly: false,
    name: "hiijack",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "0",
  },
  {
    domain: ".qidian.com",
    hostOnly: false,
    httpOnly: false,
    name: "dateTodayShowDR",
    path: "/",

    secure: false,
    session: true,
    storeId: null,
    value: "1677769679450",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709298359,
    hostOnly: false,
    httpOnly: false,
    name: "lrbc",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "1036348237%7C743607429%7C0",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1712329679.881116,
    hostOnly: false,
    httpOnly: false,
    name: "_ga_D20NXNVDG2",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "GS1.1.1677768636.2.1.1677769679.0.0.0",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709304711,
    hostOnly: false,
    httpOnly: false,
    name: "gender",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "male",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1712322634.128767,
    hostOnly: false,
    httpOnly: false,
    name: "_ga_FZMMH98S83",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "GS1.1.1677762357.2.1.1677762634.0.0.0",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709296100,
    hostOnly: false,
    httpOnly: false,
    name: "qdgd",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "1",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709296099,
    hostOnly: false,
    httpOnly: false,
    name: "navWelfareTime",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "1677760099880",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709305680.760282,
    hostOnly: false,
    httpOnly: false,
    name: "newstatisticUUID",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "1677760098_1310860957",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1712322634.134177,
    hostOnly: false,
    httpOnly: false,
    name: "_ga_PFYW0QLV3P",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "GS1.1.1677762357.2.1.1677762634.0.0.0",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1712322488.748413,
    hostOnly: false,
    httpOnly: false,
    name: "mrecUUID",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "d0d806e9dbcb949eda70c9496e5dd502",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709296098.722494,
    hostOnly: false,
    httpOnly: false,
    name: "_csrfToken",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "bOscwFwHXiKpTaaWi0BTHYiiFH6YnLDJTx2i8CRE",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1712329679.918665,
    hostOnly: false,
    httpOnly: false,
    name: "_ga_VMQL7235X0",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "GS1.1.1677768636.2.1.1677769679.0.0.0",
  },
  {
    domain: "m.qidian.com",
    hostOnly: true,
    httpOnly: false,
    name: "_yep_uuid",
    path: "/",

    secure: false,
    session: true,
    storeId: null,
    value: "92e1bad1-73f0-a3d7-aa6b-3bd812ac4179",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1677848894,
    hostOnly: false,
    httpOnly: false,
    name: "COOKIE_BOOKLIST_TIPS",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "1",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1680360714,
    hostOnly: false,
    httpOnly: false,
    name: "e1",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "%7B%22pid%22%3A%22mqd_P_qidianm%22%2C%22eid%22%3A%22%22%7D",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1680360714,
    hostOnly: false,
    httpOnly: false,
    name: "e2",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value:
      "%7B%22pid%22%3A%22mqd_P_qidianm%22%2C%22eid%22%3A%22mall_A1%22%2C%22l1%22%3A17%7D",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1712320098.722592,
    hostOnly: false,
    httpOnly: false,
    name: "fu",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "474523443",
  },
  {
    domain: ".qidian.com",
    hostOnly: false,
    httpOnly: false,
    name: "isTodayClosed",
    path: "/",

    secure: false,
    session: true,
    storeId: null,
    value: "0",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709296099,
    hostOnly: false,
    httpOnly: false,
    name: "qdrs",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "0%7C3%7C0%7C0%7C1",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709298359,
    hostOnly: false,
    httpOnly: false,
    name: "rcr",
    path: "/",

    secure: false,
    session: false,
    storeId: null,
    value: "1036348237",
  },
  {
    domain: ".qidian.com",
    expirationDate: 1709305678.24701,
    hostOnly: false,
    httpOnly: false,
    name: "supportWebp",
    path: "/",

    secure: true,
    session: false,
    storeId: null,
    value: "true",
  },
  {
    domain: ".qidian.com",
    hostOnly: false,
    httpOnly: false,
    name: "ywguid",
    path: "/",

    secure: false,
    session: true,
    storeId: null,
    value: "120045894199",
  },
  {
    domain: ".qidian.com",
    hostOnly: false,
    httpOnly: false,
    name: "ywkey",
    path: "/",

    secure: false,
    session: true,
    storeId: null,
    value: "yw3bpzu4PaP0",
  },
  {
    domain: ".qidian.com",
    hostOnly: false,
    httpOnly: false,
    name: "ywopenid",
    path: "/",

    secure: false,
    session: true,
    storeId: null,
    value: "1157C3A5948B4AFCFFFA2A98D08F1B42",
  },
];
